/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.HoaDon;
import Service.ServiceImpl.ThongKeKhachHangServiceImpl;
import Service.ServiceImpl.ThongKeServiceImpl;
import Service.ThongKeKhachHangService;
import ViewModel.SanPhamDaMuaViewModel;
import ViewModel.SoLanMuaViewModel;
import ViewModel.ThongKeViewModel;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author admin
 */
public class ThongKeView extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeViewModel
     */
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<ThongKeViewModel> listhongKe = new ArrayList<>();
    private ThongKeServiceImpl thongKeImpl = new ThongKeServiceImpl();
    private List<HoaDon> listHoaDon = new ArrayList<>();
    private DefaultTableModel dtmSoLan = new DefaultTableModel();
    private DefaultTableModel dtmDaMua = new DefaultTableModel();
    private List<SoLanMuaViewModel> listSoLanMua = new ArrayList<>();
    private List<SoLanMuaViewModel> listSearch = new ArrayList<>();
    private List<SoLanMuaViewModel> listSearchTen = new ArrayList<>();
    private List<SanPhamDaMuaViewModel> listSPDM = new ArrayList<>();
    private List<SoLanMuaViewModel> listSearchSoLuong = new ArrayList<>();
    private ThongKeKhachHangService thongKeKhachHangService = new ThongKeKhachHangServiceImpl();
    int rowoffset = 0;
    int index = 0;
    String name = "";
    int soLan;
    int fetch = 5;
    int o = 0;

    public ThongKeView() {
        initComponents();
        this.setLocationRelativeTo(null);

        TableThongKe.setModel(dtm);
        String[] heards = {"IMEI", "Mã HD", "Giá Bán", "Ngày tạo", "Giảm giá", "Giá nhập", "Thành tiền ", "Lãi"};
        dtm.setColumnIdentifiers(heards);
        listhongKe = thongKeImpl.getLisst();
        thongKeImpl.showDaTa(dtm, listhongKe);
        DecimalFormat df = new DecimalFormat("###,###,###,###");
        ThanhTien(listhongKe);
        txtDoanhThu.setText(df.format(ThanhTien(listhongKe)) + " " + "VNĐ");

        cbbNgay.removeAllItems();

        for (int i = 1; i <= 31; i++) {
            cbbNgay.addItem(i + "");

        }
        cbbThang.removeAllItems();
        for (int i = 1; i <= 12; i++) {
            cbbThang.addItem(i + "");
        }
        Calendar instance = Calendar.getInstance();
        cbbNam.removeAllItems();
        int year = instance.get(Calendar.YEAR);
        for (int i = 2000; i <= year; i++) {
            cbbNam.addItem(i + "");
        }

        tbSoLanMua.setModel(dtmSoLan);
        tbSoLanMua1.setModel(dtmDaMua);
        String daMua[] = {"IMEI", "Ten san pham", "Ten Dong", "Gia ban"};
        String soLanMua[] = {"ID", "Ten Khach Hang", "So lan mua"};
        dtmDaMua.setColumnIdentifiers(daMua);
        dtmSoLan.setColumnIdentifiers(soLanMua);
        listSoLanMua = thongKeKhachHangService.getAllSoLanMua(rowoffset);
        thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSoLanMua);

    }

    private double ThanhTien(List<ThongKeViewModel> x) {
        double tien = 0;
        for (ThongKeViewModel object : x) {// chạy list thống kê 
            tien += object.getGiaBan() - object.getGiaGiam() - object.getGiaNhap();
        }
        return tien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableThongKe = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabelTong = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtDaonhThu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLaiThang = new javax.swing.JLabel();
        txtDoanhThu = new javax.swing.JLabel();
        cbbNgay = new javax.swing.JComboBox<>();
        cbbThang = new javax.swing.JComboBox<>();
        cbbNam = new javax.swing.JComboBox<>();
        cbbNTN = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNTNam = new javax.swing.JLabel();
        txtThang = new javax.swing.JLabel();
        btnDong = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnXuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbSoLanMua1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSoLanMua = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setText("Tìm kiếm ");

        TableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        TableThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableThongKeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableThongKe);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("THỐNG KÊ DOANH THU");

        jLabelTong.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelTong.setText("Tổng doanh thu:");
        jLabelTong.setToolTipText("");

        txtDaonhThu.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtDaonhThu.setText("Doanh Thu Theo ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText(":");

        txtLaiThang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtLaiThang.setForeground(new java.awt.Color(255, 0, 0));

        txtDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDoanhThu.setForeground(new java.awt.Color(255, 0, 0));

        cbbNgay.setBackground(new java.awt.Color(255, 153, 0));
        cbbNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cbbNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNgayActionPerformed(evt);
            }
        });

        cbbThang.setBackground(new java.awt.Color(255, 153, 0));
        cbbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng" }));

        cbbNam.setBackground(new java.awt.Color(255, 153, 0));
        cbbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm" }));
        cbbNam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbbNam.setDoubleBuffered(true);

        cbbNTN.setBackground(new java.awt.Color(255, 153, 0));
        cbbNTN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tháng", "Năm" }));
        cbbNTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNTNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tìm kiếm theo");

        txtNTNam.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N

        txtThang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnDong.setText("Đóng ");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel2.setText("Theo ngày ");

        jLabel3.setText("Theo tháng ");

        jLabel6.setText("Theo năm");

        btnXuat.setText("Xuất Execl");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(292, 292, 292)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbNTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(187, 187, 187))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(523, 523, 523))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(82, 82, 82)
                                                .addComponent(jLabel6)))
                                        .addGap(140, 140, 140)
                                        .addComponent(jLabel5)
                                        .addGap(187, 187, 187)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelTong, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(txtDaonhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNTNam, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLaiThang, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnXuat)
                .addGap(34, 34, 34)
                .addComponent(btnDong)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbNTN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNTNam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDaonhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtThang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLaiThang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTong)
                    .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(btnXuat))
                .addGap(22, 22, 22))
        );

        jTabbedPane2.addTab("Doanh Thu", jPanel1);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("San Pham Da Mua"));

        tbSoLanMua1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSoLanMua1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSoLanMua1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbSoLanMua1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setText("Thong ke khach hang");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("So lan mua"));

        tbSoLanMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSoLanMua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSoLanMuaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbSoLanMua);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("||<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText(">||");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiem theo ten: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addGap(25, 25, 25))
        );

        jTabbedPane2.addTab("Khach hang", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void cbbNTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNTNActionPerformed
        // TODO add your handling code here:
        List<ThongKeViewModel> thongKe = new ArrayList<>();
        String ngay = cbbNgay.getSelectedItem() + "";
        String thang = cbbThang.getSelectedItem() + "";
        String nam = cbbNam.getSelectedItem() + "";
        String ntn = ngay + "-" + thang + "-" + nam;
        thongKe = thongKeImpl.searchNgayThangNam(ntn, listhongKe);
        if (cbbNTN.getSelectedItem().equals("Tháng")) {
            thongKe = thongKeImpl.searchThang(cbbThang.getSelectedItem() + "", listhongKe);
            txtNTNam.setText("Tháng");
            txtThang.setText(thang);
        } else if (cbbNTN.getSelectedItem().equals("Năm")) {

            thongKe = thongKeImpl.searchNam(cbbNam.getSelectedItem() + "", listhongKe);

            txtNTNam.setText("Năm");
            txtThang.setText(nam);
        } else if (cbbNTN.getSelectedItem().equals("Ngày")) {
            thongKe = thongKeImpl.searchNgay(cbbNgay.getSelectedItem() + "", listhongKe);
            txtNTNam.setText("Ngày");
            txtThang.setText(ngay);

            thongKeImpl.showDaTa(dtm, thongKe);
        } else ;

        DecimalFormat df = new DecimalFormat("###,###,###,###");

        txtLaiThang.setText(df.format(ThanhTien(thongKe)) + " " + "VNĐ");

        thongKeImpl.showDaTa(dtm, thongKe);
    }//GEN-LAST:event_cbbNTNActionPerformed

    private void cbbNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNgayActionPerformed

    private void TableThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableThongKeMouseClicked

    }//GEN-LAST:event_TableThongKeMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (!txtSearch.getText().isEmpty() || !txtSearch.getText().isBlank()) {
            name = txtSearch.getText();
            listSearch = thongKeKhachHangService.searchTen(name, rowoffset);
            listSearchTen = thongKeKhachHangService.searchTen(name, rowoffset);
            try {
                thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSearch);
            } catch (Exception e) {
                thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSearch);
            }
        }

        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            listSoLanMua = thongKeKhachHangService.getAllSoLanMua(rowoffset);
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, thongKeKhachHangService.getAllSoLanMua(rowoffset));
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tbSoLanMua1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSoLanMua1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSoLanMua1MouseClicked

    private void tbSoLanMuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSoLanMuaMouseClicked
        // TODO add your handling code here:
        int row = tbSoLanMua.getSelectedRow();
        String id = thongKeKhachHangService.getAllSoLanMua(rowoffset).get(row).getID();
        listSPDM = thongKeKhachHangService.getAllSPDM(id);
        thongKeKhachHangService.showDataTableSPDM(dtmDaMua, listSPDM);
    }//GEN-LAST:event_tbSoLanMuaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            index = 0;        // TODO add your handling code here:
            int c = thongKeKhachHangService.getAllSoLanMuaKPT().size() % fetch;
            rowoffset = 0;
            listSoLanMua = thongKeKhachHangService.getAllSoLanMua(rowoffset);
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSoLanMua);
        } else {
            index = 0;        // TODO add your handling code here:
            int c = thongKeKhachHangService.getAllSoLanMuaKPT().size() % fetch;
            rowoffset = 0;
            listSearchTen = thongKeKhachHangService.searchTen(name, rowoffset);
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSearchTen);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty()) {
            index--;
            rowoffset -= 5;
            if (rowoffset < 0) {
                int c = thongKeKhachHangService.getAllSoLanMuaKPT().size() % fetch;
                rowoffset = thongKeKhachHangService.getAllSoLanMuaKPT().size() - c;
                index = o;
            }
            listSoLanMua = thongKeKhachHangService.getAllSoLanMua(rowoffset);
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSoLanMua);

        } else {

            if (!txtSearch.getText().isEmpty()) {
                index--;
                rowoffset -= 5;
                if (rowoffset < 0) {
                    int c = listSearch.size() % fetch;
                    rowoffset = listSearch.size() - c;
                    index = o;

                }

                thongKeKhachHangService.showDataTableSoLan(dtmSoLan, thongKeKhachHangService.searchTen(name, rowoffset));

            } else {
                index--;
                rowoffset -= 5;

                if (rowoffset < 0) {
                    int c = listSearch.size() % fetch;
                    rowoffset = listSearch.size() - c;
                    index = o;

                }

                thongKeKhachHangService.showDataTableSoLan(dtmSoLan, thongKeKhachHangService.searchSoLanMua(soLan, rowoffset));
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty()) {
            index++;
            rowoffset += 5;
            if (rowoffset > thongKeKhachHangService.getAllSoLanMuaKPT().size() - 1) {
                rowoffset = 0;
                index = 0;
            }
            listSoLanMua = thongKeKhachHangService.getAllSoLanMuaKPT();
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, thongKeKhachHangService.getAllSoLanMua(rowoffset));

        } else {

            if (!txtSearch.getText().isEmpty()) {
                index++;
                rowoffset += 5;
                if (rowoffset > listSearchTen.size()) {

                    rowoffset = 0;
                    index = 0;

                }

                thongKeKhachHangService.showDataTableSoLan(dtmSoLan, thongKeKhachHangService.searchTen(name, rowoffset));

            } else {
                index++;
                rowoffset += 5;

                if (rowoffset > listSoLanMua.size()) {
                    rowoffset = 0;
                    index = 0;

                }

                thongKeKhachHangService.showDataTableSoLan(dtmSoLan, thongKeKhachHangService.searchSoLanMua(soLan, rowoffset));

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().isEmpty() || txtSearch.getText().isBlank()) {
            index = o;        // TODO add your handling code here:
            int c = thongKeKhachHangService.getAllSoLanMuaKPT().size() % fetch;
            rowoffset = thongKeKhachHangService.getAllSoLanMuaKPT().size() - c;
            listSoLanMua = thongKeKhachHangService.getAllSoLanMua(rowoffset);
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSoLanMua);
        } else {

            // TODO add your handling code here:
            int c = listSearchTen.size() / fetch;
            index = listSearchTen.size() / fetch;
            rowoffset = thongKeKhachHangService.searchTen(name, rowoffset).size() - c;
            listSearchTen = thongKeKhachHangService.searchTen(name, rowoffset);
            thongKeKhachHangService.showDataTableSoLan(dtmSoLan, listSearchTen);

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        try {

            XSSFWorkbook worbook = new XSSFWorkbook();
            XSSFSheet sheet = worbook.createSheet("Doanh thu");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("IMEI");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Mã HD");
            cell = row.createCell(3, CellType.NUMERIC);
            cell.setCellValue("Giá Bán");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ngày tạo ");
            cell = row.createCell(5, CellType.NUMERIC);
            cell.setCellValue("Giá giảm ");
            cell = row.createCell(6, CellType.NUMERIC);
            cell.setCellValue("Gía nhập ");
//            cell = row.createCell(6, CellType.STRING);
//            cell.setCellValue("Thành tiền ");
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Lãi ");

            for (int i = 0; i < listhongKe.size(); i++) {

                row = sheet.createRow(4 + i);// khoảng cách từ đầu đến dòng imei
                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1); // số 1
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(listhongKe.get(i).getImei());
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(listhongKe.get(i).getMaHD());

                cell = row.createCell(3, CellType.NUMERIC);
                cell.setCellValue(listhongKe.get(i).getGiaBan());
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(String.valueOf(listhongKe.get(i).getNgayTao()));
                cell = row.createCell(5, CellType.NUMERIC);
                cell.setCellValue(listhongKe.get(i).giaGiam());
                cell = row.createCell(6, CellType.NUMERIC);
                cell.setCellValue(listhongKe.get(i).getGiaNhap());
                cell = row.createCell(7, CellType.NUMERIC);
                cell.setCellValue((listhongKe.get(i).getGiaBan()) - (listhongKe.get(i).giaGiam()) - (listhongKe.get(i).getGiaNhap()));

            }

            File f = new File("C:\\Execl\\doanh.xlsx");
            try {
                FileOutputStream fiss = new FileOutputStream(f);
                worbook.write(fiss);
                fiss.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();

            } catch (IOException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "In thành công ");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi mở  file");

        }
    }//GEN-LAST:event_btnXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableThongKe;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnXuat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbNTN;
    private javax.swing.JComboBox<String> cbbNam;
    private javax.swing.JComboBox<String> cbbNgay;
    private javax.swing.JComboBox<String> cbbThang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbSoLanMua;
    private javax.swing.JTable tbSoLanMua1;
    private javax.swing.JLabel txtDaonhThu;
    private javax.swing.JLabel txtDoanhThu;
    private javax.swing.JLabel txtLaiThang;
    private javax.swing.JLabel txtNTNam;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtThang;
    // End of variables declaration//GEN-END:variables

//    private void tong() {
//        DecimalFormat x = new DecimalFormat("###,###,###");
//        double Tong = 0;
//        for (int i = 0; i < TableThongKe.getRowCount(); i++) {
//            Tong += Double.parseDouble(TableThongKe.getValueAt(i, 2).toString());
////              Tong+= Integer.parseInt(TableThongKe.getValueAt(i,2).toString());
//
//        }
//        jLabelTong.setText("Tổng doanh thu: " + x.format(Tong) + " " + "VND");
//    }
}
