/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.ServiceImpl.HoaDonImpl;
import ViewModel.VIewModelSanPhamHoaDon;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import ViewModel.ViewModelHoaDon;

/**
 *
 * @author PC
 */
public class ViewHoaDon extends javax.swing.JFrame {

    private DefaultTableModel tableHoaDon = new DefaultTableModel();
    private DefaultTableModel tableSanPhamHD = new DefaultTableModel();
    private DefaultComboBoxModel ccbTim = new DefaultComboBoxModel();
    private DefaultComboBoxModel ccbSapXep = new DefaultComboBoxModel();
    private List<ViewModelHoaDon> listGetAll = new ArrayList<>();
    private List<ViewModelHoaDon> listSearch = new ArrayList<>();
    private List<ViewModelHoaDon> listSort = new ArrayList<>();
    private List<String> ccbFind = new ArrayList<>();
    private List<VIewModelSanPhamHoaDon> listGetSP = new ArrayList<>();
    private List<String> ccb = new ArrayList<>();
    private HoaDonImpl sv = new HoaDonImpl();
    String name = "";
    int TrangThai = 0;

    public ViewHoaDon() {
        initComponents();
        tlbHoaDon.setModel(tableHoaDon);
        tlbSanPham.setModel(tableSanPhamHD);
        ccbLoc.setModel(ccbSapXep);
        ccb.add("Tất Cả");
        ccb.add("Theo giá từ thấp lên cao");
        ccb.add("Theo giá từ cao xuống thấp");
        ccb.add("Chưa Thanh Toán");
        ccb.add("Đã Thanh Toán");

        for (String string : ccb) {
            ccbSapXep.addElement(string);
        }
        for (String string : ccbFind) {
            ccbTim.addElement(string);
        }

        String[] heaaderHoaDon = {"Mã HD", "Tên NV", "Tên KH", "Ngày Tạo", "Mã Khuyến Mại", "Giá Giảm", "Tổng Tiền", "Trạng Thái", "Tổng số SP"};
        tableHoaDon.setColumnIdentifiers(heaaderHoaDon);
        String[] headerSanPham = {"Mã HD ", "Mã DT", "Tên SP", "Hãng", "Dòng", "Giá Bán", "Độ Mới", "Mô tả"};
        tableSanPhamHD.setColumnIdentifiers(headerSanPham);

        listSearch = sv.getAll(listGetAll);
        sv.showData(listSearch, tableHoaDon);

        int TrangThai = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ccbLoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbSanPham = new javax.swing.JTable();
        btnDong = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Hóa Đơn");

        jLabel2.setText("Tìm Kiếm:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        jLabel3.setText("Sắp Xếp Theo:");

        ccbLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ccbLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccbLocActionPerformed(evt);
            }
        });

        tlbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HĐ", "Tên NV", "Tên KH", "Ngày Tạo", "Mã Khuyến Mại", "Tổng Tiền", "Trạng Thái", "Tổng Số Sản Phẩm"
            }
        ));
        tlbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbHoaDon);

        tlbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ĐT", "Mã HĐ", "Tên SP", "Hãng", "Dòng", "Giá Bán", "Độ Mới", "Mô Tả"
            }
        ));
        jScrollPane2.setViewportView(tlbSanPham);

        btnDong.setText("Exit");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Danh Sách Hóa Đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Sản Phẩm");

        jButton1.setText("Xuất Hóa Đơn");

        jButton2.setText("Xuất Danh Sách Hóa Đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(517, 517, 517))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(ccbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(101, 101, 101)
                                .addComponent(jButton1)
                                .addGap(105, 105, 105)
                                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ccbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tlbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbHoaDonMouseClicked
        // TODO add your handling code here:
        int row = 0;
        if (TrangThai == 1) {

            if (ccbLoc.getSelectedIndex() == 0) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSearch.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 1) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSearch.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 2) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSearch.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 3) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSort.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 4) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSort.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
        } else if (TrangThai == 0) {
            if (ccbLoc.getSelectedIndex() == 0) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSearch.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 1) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSearch.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 2) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSearch.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 3) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSort.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
            if (ccbLoc.getSelectedIndex() == 4) {
                row = tlbHoaDon.getSelectedRow();
                String mahd = listSort.get(row).getMaHD();
                listGetSP = sv.getAllSp(mahd);
                sv.showData1(listGetSP, tableSanPhamHD);
            }
        }

    }//GEN-LAST:event_tlbHoaDonMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        name = txtTimKiem.getText();
        sv.showData(sv.searchHoaDon(name), tableHoaDon);
        listSearch = sv.searchHoaDon(name);
        TrangThai = 1;
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //ViewHoaDon view = new ViewHoaDon();
        //view.setVisible(true);
    }//GEN-LAST:event_btnDongActionPerformed

    private void ccbLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccbLocActionPerformed
        // TODO add your handling code here:

        if (TrangThai == 0) {
            if (ccbLoc.getSelectedIndex() == 0) {
                sv.showData(listSearch, tableHoaDon);
                TrangThai = 0;

            }

            if (ccbLoc.getSelectedIndex() == 1) {
                sv.giaCaoXuongThap(listSearch);
                sv.showData(listSearch, tableHoaDon);
                TrangThai = 0;
            }

            if (ccbLoc.getSelectedIndex() == 2) {

                sv.giaThapLenCao(listSearch);
                sv.showData(listSearch, tableHoaDon);
                TrangThai = 0;
            }

            if (ccbLoc.getSelectedIndex() == 3) {
                listSort.removeAll(listSort);
                for (ViewModelHoaDon viewModelHoaDon : listSearch) {
                    if (viewModelHoaDon.getTrangThai() == 0) {
                        listSort.add(viewModelHoaDon);
                    }
                }
                sv.showData(listSort, tableHoaDon);
            }

            if (ccbLoc.getSelectedIndex() == 4) {

                listSort.removeAll(listSort);
                for (ViewModelHoaDon viewModelHoaDon : listSearch) {
                    if (viewModelHoaDon.getTrangThai() == 1) {
                        listSort.add(viewModelHoaDon);
                    }
                }
                sv.showData(listSort, tableHoaDon);
            }
        }

        if (TrangThai == 1) {

            if (ccbLoc.getSelectedIndex() == 0) {
                sv.showData(listSearch, tableHoaDon);
                TrangThai = 0;

            }

            if (ccbLoc.getSelectedIndex() == 1) {
                sv.giaCaoXuongThap(listSearch);
                sv.showData(listSearch, tableHoaDon);
                TrangThai = 1;
            }

            if (ccbLoc.getSelectedIndex() == 2) {

                sv.giaThapLenCao(listSearch);
                sv.showData(listSearch, tableHoaDon);
                TrangThai = 1;
            }

            if (ccbLoc.getSelectedIndex() == 3) {
                listSort.removeAll(listSort);
                for (ViewModelHoaDon viewModelHoaDon : listSearch) {
                    if (viewModelHoaDon.getTrangThai() == 0) {
                        listSort.add(viewModelHoaDon);
                    }
                }
                sv.showData(listSort, tableHoaDon);
            }

            if (ccbLoc.getSelectedIndex() == 4) {

                listSort.removeAll(listSort);
                for (ViewModelHoaDon viewModelHoaDon : listSearch) {
                    if (viewModelHoaDon.getTrangThai() == 1) {
                        listSort.add(viewModelHoaDon);
                    }
                }
                sv.showData(listSort, tableHoaDon);
            }

        }
    }//GEN-LAST:event_ccbLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> ccbLoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tlbHoaDon;
    private javax.swing.JTable tlbSanPham;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
