/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.SanPham;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author haha
 */
public class ViewThemSanPham extends javax.swing.JDialog {

    List<Integer> ix = new ArrayList<>();

    /**
     * Creates new form ViewThemSanPham
     */
    public ViewThemSanPham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public List<Integer> viewx() {
        return ix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbHDH = new javax.swing.JCheckBox();
        cbCamera = new javax.swing.JCheckBox();
        cbTienIch = new javax.swing.JCheckBox();
        cbKetNoi = new javax.swing.JCheckBox();
        cbMauSac = new javax.swing.JCheckBox();
        cbThietKe = new javax.swing.JCheckBox();
        cbBoNho = new javax.swing.JCheckBox();
        cbViXuLy = new javax.swing.JCheckBox();
        cbManHinh = new javax.swing.JCheckBox();
        cbPin = new javax.swing.JCheckBox();
        btnXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Các thông tin muốn thêm"));

        cbHDH.setText("Hệ điều hành");

        cbCamera.setText("Camera");

        cbTienIch.setText("Tiện ích");

        cbKetNoi.setText("Kết nối");

        cbMauSac.setText("Màu sắc");

        cbThietKe.setText("Thiết kế");

        cbBoNho.setText("Bộ nhớ");
        cbBoNho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBoNhoActionPerformed(evt);
            }
        });

        cbViXuLy.setText("Vi xử lý");

        cbManHinh.setText("Màn hình");

        cbPin.setText("Pin");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbHDH)
                            .addComponent(cbCamera)
                            .addComponent(cbTienIch)
                            .addComponent(cbKetNoi)
                            .addComponent(cbMauSac))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPin)
                            .addComponent(cbManHinh)
                            .addComponent(cbViXuLy)
                            .addComponent(cbBoNho)
                            .addComponent(cbThietKe)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnXacNhan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHDH)
                    .addComponent(cbThietKe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCamera)
                    .addComponent(cbBoNho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTienIch)
                    .addComponent(cbViXuLy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKetNoi)
                    .addComponent(cbManHinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMauSac)
                    .addComponent(cbPin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnXacNhan)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbBoNhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBoNhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBoNhoActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        if (cbBoNho.isSelected()) {
            ix.add(1);
        }
        if (cbCamera.isSelected()) {
            ix.add(2);
        }
        if (cbHDH.isSelected()) {
            ix.add(3);
        }
        if (cbKetNoi.isSelected()) {
            ix.add(4);
        }
        if (cbManHinh.isSelected()) {
            ix.add(5);
        }
        if (cbMauSac.isSelected()) {
            ix.add(6);
        }
        if (cbPin.isSelected()) {
            ix.add(7);
        }
        if (cbThietKe.isSelected()) {
            ix.add(8);
        }
        if (cbViXuLy.isSelected()) {
            ix.add(9);
        }
        if (ix.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn");
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewThemSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewThemSanPham dialog = new ViewThemSanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JCheckBox cbBoNho;
    private javax.swing.JCheckBox cbCamera;
    private javax.swing.JCheckBox cbHDH;
    private javax.swing.JCheckBox cbKetNoi;
    private javax.swing.JCheckBox cbManHinh;
    private javax.swing.JCheckBox cbMauSac;
    private javax.swing.JCheckBox cbPin;
    private javax.swing.JCheckBox cbThietKe;
    private javax.swing.JCheckBox cbTienIch;
    private javax.swing.JCheckBox cbViXuLy;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
